modules = $(shell ls app)

migrate-modules := $(addprefix migrate-, $(modules))
rollup-modules := $(addprefix rollup-, $(modules))
wire-modules := $(addprefix wire-, $(modules))
config-modules := $(addprefix config-, $(modules))
ent-modules := $(addprefix ent-, $(modules))
proto-modules := $(addprefix proto-, $(modules))

API_PROTO_FILES=$(shell find api -name *.proto)

$(migrate-modules):
	go run ./app/$(patsubst migrate-%,%,$@)/cmd migrate up -c ./configs/$(patsubst migrate-%,%,$@) --dir ./app/$(patsubst migrate-%,%,$@)/db/migration

$(rollup-modules):
	go run ./app/$(patsubst rollup-%,%,$@)/cmd migrate down -c ./configs/$(patsubst rollup-%,%,$@) --dir ./app/$(patsubst rollup-%,%,$@)/db/migration

$(wire-modules):
	wire ./app/$(patsubst wire-%,%,$@)/cmd

$(ent-modules):
	go generate ./app/$(patsubst ent-%,%,$@)/internal/data/ent/generate.go

$(config-modules):
	protoc --proto_path=./app/$(patsubst config-%,%,$@)/internal/conf \
	       --proto_path=./third_party \
 	       --go_out=paths=source_relative:./app/$(patsubst config-%,%,$@)/internal/conf \
	       $(shell find ./app/$(patsubst config-%,%,$@)/internal/conf -name *.proto)

$(proto-modules):
	@service=$(patsubst proto-%,%,$@); \
	proto_files=$$(find ./api/$$service/ -name '*.proto'); \
	protoc_flags=""; \
	if grep -ql "google.api.http" $$proto_files 2>/dev/null; then \
		mkdir -p ./openapi/$$service; \
		protoc_flags="$$protoc_flags --openapiv2_out=allow_merge,include_package_in_tags=false,merge_file_name=openapi.json:./openapi/$$service"; \
	fi; \
	if grep -ql "buf/validate" $$proto_files 2>/dev/null; then \
		protoc_flags="$$protoc_flags --validate_out=paths=source_relative,lang=go:."; \
	fi; \
	set -x; \
	protoc --proto_path=. \
	       --proto_path=./third_party \
	       --go_out=paths=source_relative:. \
	       --go-http_out=paths=source_relative:. \
	       --go-grpc_out=paths=source_relative:. \
	       $$protoc_flags \
	       $$proto_files
